version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    image: 381492253717.dkr.ecr.us-east-2.amazonaws.com/ee547/mail-system:latest

  backend2:
    image: 381492253717.dkr.ecr.us-east-2.amazonaws.com/ee547/mail-system:latest

  backend3:
    image: 381492253717.dkr.ecr.us-east-2.amazonaws.com/ee547/mail-system:latest

  classifier:
    image: 381492253717.dkr.ecr.us-east-2.amazonaws.com/ee547/classifier:latest
